#index:
#    path: /
#    controller: App\Controller\DefaultController::index

city_list:
  path: /cities
  controller: App\Controller\CityController::list
  methods: [GET]

hostel_active_city:
  path: /hostels/active/{cityId}
  controller: App\Controller\HostelController::listByCity